[package]
name = "xohimnoob"
version = "0.1.0"
authors = ["Andy Meneely <andy@se.rit.edu>"]
edition = "2021"



[dependencies]
sha2 = "0.9.8"
base64 = "0.13.0"
hex-literal = "0.3.3"
rand = "0.8.4"
regex = "1.5.4"
serde = { version = "1.0.130", features = ["derive"] }
serde_yaml = "0.8.21"
